spring.application.name=api-gateway
server.port=8080

# ==================================================
# EUREKA
# ==================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# =====================================
# GLOBAL CORS 
# =====================================

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

# ==================================================
# ROUTES
# ==================================================

# PATIENT
spring.cloud.gateway.server.webflux.routes[0].id=patient-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/patients/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=0

# DOCTOR
spring.cloud.gateway.server.webflux.routes[1].id=doctor-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://DOCTOR-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/doctors/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=0

# APPOINTMENT
spring.cloud.gateway.server.webflux.routes[2].id=appointment-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/appointments/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=0

# SLOT
spring.cloud.gateway.server.webflux.routes[3].id=slot-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/slots/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=0

# PRESCRIPTION
spring.cloud.gateway.server.webflux.routes[4].id=prescription-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://PRESCRIPTION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/prescriptions/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=0

# AUTH
spring.cloud.gateway.server.webflux.routes[5].id=auth-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=StripPrefix=0

# PAYMENT
spring.cloud.gateway.server.webflux.routes[6].id=payment-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/payments/**
spring.cloud.gateway.server.webflux.routes[6].filters[0]=StripPrefix=0

# NOTIFICATION
spring.cloud.gateway.server.webflux.routes[7].id=notification-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/notifications/**
spring.cloud.gateway.server.webflux.routes[7].filters[0]=StripPrefix=0

#==================================================
#SWAGGER ROUTES
#===================================================
spring.cloud.gateway.server.webflux.routes[8].id=auth-openapi
spring.cloud.gateway.server.webflux.routes[8].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/v3/api-docs/auth
spring.cloud.gateway.server.webflux.routes[8].filters[0]=RewritePath=/v3/api-docs/auth,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[9].id=patient-openapi
spring.cloud.gateway.server.webflux.routes[9].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/v3/api-docs/patient
spring.cloud.gateway.server.webflux.routes[9].filters[0]=RewritePath=/v3/api-docs/patient,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[10].id=doctor-openapi
spring.cloud.gateway.server.webflux.routes[10].uri=lb://DOCTOR-SERVICE
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/v3/api-docs/doctor
spring.cloud.gateway.server.webflux.routes[10].filters[0]=RewritePath=/v3/api-docs/doctor,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[11].id=appointment-openapi
spring.cloud.gateway.server.webflux.routes[11].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/v3/api-docs/appointment
spring.cloud.gateway.server.webflux.routes[11].filters[0]=RewritePath=/v3/api-docs/appointment,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[12].id=payment-openapi
spring.cloud.gateway.server.webflux.routes[12].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/v3/api-docs/payment
spring.cloud.gateway.server.webflux.routes[12].filters[0]=RewritePath=/v3/api-docs/payment,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[13].id=prescription-openapi
spring.cloud.gateway.server.webflux.routes[13].uri=lb://PRESCRIPTION-SERVICE
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/v3/api-docs/prescription
spring.cloud.gateway.server.webflux.routes[13].filters[0]=RewritePath=/v3/api-docs/prescription,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[14].id=notification-openapi
spring.cloud.gateway.server.webflux.routes[14].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/v3/api-docs/notification
spring.cloud.gateway.server.webflux.routes[14].filters[0]=RewritePath=/v3/api-docs/notification,/v3/api-docs

# ==================================================
# SWAGGER AGGREGATION
# ==================================================

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/auth

springdoc.swagger-ui.urls[1].name=patient-service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/patient

springdoc.swagger-ui.urls[2].name=doctor-service
springdoc.swagger-ui.urls[2].url=/v3/api-docs/doctor

springdoc.swagger-ui.urls[3].name=appointment-service
springdoc.swagger-ui.urls[3].url=/v3/api-docs/appointment

springdoc.swagger-ui.urls[4].name=payment-service
springdoc.swagger-ui.urls[4].url=/v3/api-docs/payment

springdoc.swagger-ui.urls[5].name=prescription-service
springdoc.swagger-ui.urls[5].url=/v3/api-docs/prescription

springdoc.swagger-ui.urls[6].name=notification-service
springdoc.swagger-ui.urls[6].url=/v3/api-docs/notification

