// src/utils/pdfUtils.js
// Generates PDF reports from HTML elements using jsPDF + html2canvas.
// Also provides a pure-data PDF builder for prescriptions.

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Capture a DOM element and download as PDF.
 * @param {string} elementId - ID of the HTML element to capture
 * @param {string} filename  - Output filename (without .pdf)
 */
export async function downloadElementAsPDF(elementId, filename = 'report') {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`Element #${elementId} not found`);
    return;
  }
  const canvas = await html2canvas(element, { scale: 2, useCORS: true });
  const imgData = canvas.toDataURL('image/png');

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const imgWidth = pageWidth - 20;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  let y = 10;
  let heightLeft = imgHeight;

  pdf.addImage(imgData, 'PNG', 10, y, imgWidth, imgHeight);
  heightLeft -= pageHeight - 10;

  while (heightLeft > 0) {
    y = heightLeft - imgHeight;
    pdf.addPage();
    pdf.addImage(imgData, 'PNG', 10, y, imgWidth, imgHeight);
    heightLeft -= pageHeight;
  }

  pdf.save(`${filename}.pdf`);
}

/**
 * Build a prescription PDF directly from data (no DOM capture needed).
 */
export function downloadPrescriptionPDF(prescription) {
  const doc = new jsPDF();
  const LINE = 10;
  let y = 20;

  doc.setFontSize(18);
  doc.setTextColor(33, 150, 243);
  doc.text('MediTrack — Prescription', 105, y, { align: 'center' });
  y += LINE * 1.5;

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  const fields = [
    ['Prescription ID', prescription.id],
    ['Patient Name', prescription.patientName],
    ['Doctor Name', `Dr. ${prescription.doctorName}`],
    ['Appointment ID', prescription.appointmentId],
    ['Prescription Date', prescription.prescriptionDate],
    ['Follow-up Date', prescription.followUpDate],
    ['Diagnosis', prescription.diagnosis],
    ['Medicines', prescription.medicines],
    ['Notes', prescription.notes || 'N/A'],
  ];

  fields.forEach(([label, value]) => {
    doc.setFont(undefined, 'bold');
    doc.text(`${label}:`, 20, y);
    doc.setFont(undefined, 'normal');
    const lines = doc.splitTextToSize(String(value ?? ''), 130);
    doc.text(lines, 70, y);
    y += LINE * lines.length;
  });

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text('Generated by MediTrack Healthcare System', 105, 285, { align: 'center' });

  doc.save(`prescription_${prescription.id}.pdf`);
}